PKGDIR          ?= ..
L4DIR           ?= $(PKGDIR)/../..

TARGET                   = crypt-server
SRC_CC_crypt-server = server.cc
REQUIRES_LIBS            = cxx_libc_io cxx_io

include $(L4DIR)/mk/prog.mk

